apiVersion: apps/v1
# my version

kind: Deployment
# The type of object we want to create;

metadata:
  # config options for the object we are about to create
  name: comments-depl
  # then the pods is created, give it a name of it ... "posts"
  # we run only one container with the same name

spec:
  # the exact attributes we want to apply to the object we are about to create
  replicas: 1
  selector:
    matchLabels:
      app: comments
  template:
    metadata:
      labels:
        app: comments
    spec:
      containers:
        - name: comments
          image: stanislavdashkov/comments
---
apiVersion: v1 #my version
kind: Service #The type of object we want to create;
metadata: #config options for the object we are about to create
  name: comments-srv
spec:
  type: ClusterIP #get ClusterIp by default
  selector:
    app: comments
  ports:
    - name: comments
      protocol: TCP
      port: 4001
      targetPort: 4001
