apiVersion: apps/v1
# my version

kind: Deployment
# The type of object we want to create;

metadata:
  # config options for the object we are about to create
  name: event-bus-depl
  # then the pods is created, give it a name of it ... "posts"
  # we run only one container with the same name

spec:
  # the exact attributes we want to apply to the object we are about to create
  replicas: 1
  selector:
    matchLabels:
      app: event-bus
  template:
    metadata:
      labels:
        app: event-bus
    spec:
      containers:
        - name: event-bus
          image: stanislavdashkov/event-bus
---
apiVersion: v1 #my version
kind: Service #The type of object we want to create;
metadata: #config options for the object we are about to create
  name: event-bus-srv
spec:
  type: ClusterIP #get ClusterIp by default
  selector:
    app: event-bus
  ports:
    - name: event-bus
      protocol: TCP
      port: 4005
      targetPort: 4005
