version: "3"
services:
  redis-server:
    image: "redis"
  node-app:
    restart:
      always
      #possible variants
      # 1-'no', 2-always
      # 3-on-failure  4-unless-stopped
    build: .
    ports:
      - "4001:8081" #from to
